/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const BirdLazyImport = createFileRoute('/$bird')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const BirdLazyRoute = BirdLazyImport.update({
  path: '/$bird',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/$bird.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$bird': {
      id: '/$bird'
      path: '/$bird'
      fullPath: '/$bird'
      preLoaderRoute: typeof BirdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  BirdLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$bird"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/$bird": {
      "filePath": "$bird.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
