name: Tests
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      # To allow for private packages to be downloaded
      - name: Install dependencies
        run: npm ci
      - name: Run Linter
        run: npm run lint
